substitutions:
  display_name: lohas4

esphome:
  name: lohas4
  platform: ESP8266
  board: esp01_1m


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: lohas4_AP
    password: password
    ap_timeout: 3min    

logger:

ota:

captive_portal:  

web_server: 

api:

switch:
  - platform: restart
    name: lohas4 Restart

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO14
    max_power: .3
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12
    max_power: .8

light:
  - platform: rgbww
    name: lohas4
    id: lohas4
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 1s
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
